sudo: required

language: go
services:
    - docker
install:
  - make build
  - make docker-build
script:
  - make test

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make docker-push ;
    fi
